// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"csjk-bk/models"
)

// GetAlertLabelsHandlerFunc turns a function with the right signature into a get alert labels handler
type GetAlertLabelsHandlerFunc func(GetAlertLabelsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAlertLabelsHandlerFunc) Handle(params GetAlertLabelsParams) middleware.Responder {
	return fn(params)
}

// GetAlertLabelsHandler interface for that can handle valid get alert labels params
type GetAlertLabelsHandler interface {
	Handle(GetAlertLabelsParams) middleware.Responder
}

// NewGetAlertLabels creates a new http.Handler for the get alert labels operation
func NewGetAlertLabels(ctx *middleware.Context, handler GetAlertLabelsHandler) *GetAlertLabels {
	return &GetAlertLabels{Context: ctx, Handler: handler}
}

/*
	GetAlertLabels swagger:route GET /alerts/label/{labelname}/values alert getAlertLabels

获取所有报警标签的所有标签值.

获取所有报警标签的所有标签值.
*/
type GetAlertLabels struct {
	Context *middleware.Context
	Handler GetAlertLabelsHandler
}

func (o *GetAlertLabels) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAlertLabelsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAlertLabelsOKBody get alert labels o k body
//
// swagger:model GetAlertLabelsOKBody
type GetAlertLabelsOKBody struct {
	models.CommonResponse

	// results
	Results []string `json:"results"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetAlertLabelsOKBody) UnmarshalJSON(raw []byte) error {
	// GetAlertLabelsOKBodyAO0
	var getAlertLabelsOKBodyAO0 models.CommonResponse
	if err := swag.ReadJSON(raw, &getAlertLabelsOKBodyAO0); err != nil {
		return err
	}
	o.CommonResponse = getAlertLabelsOKBodyAO0

	// GetAlertLabelsOKBodyAO1
	var dataGetAlertLabelsOKBodyAO1 struct {
		Results []string `json:"results"`
	}
	if err := swag.ReadJSON(raw, &dataGetAlertLabelsOKBodyAO1); err != nil {
		return err
	}

	o.Results = dataGetAlertLabelsOKBodyAO1.Results

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetAlertLabelsOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getAlertLabelsOKBodyAO0, err := swag.WriteJSON(o.CommonResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getAlertLabelsOKBodyAO0)
	var dataGetAlertLabelsOKBodyAO1 struct {
		Results []string `json:"results"`
	}

	dataGetAlertLabelsOKBodyAO1.Results = o.Results

	jsonDataGetAlertLabelsOKBodyAO1, errGetAlertLabelsOKBodyAO1 := swag.WriteJSON(dataGetAlertLabelsOKBodyAO1)
	if errGetAlertLabelsOKBodyAO1 != nil {
		return nil, errGetAlertLabelsOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetAlertLabelsOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get alert labels o k body
func (o *GetAlertLabelsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.CommonResponse
	if err := o.CommonResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this get alert labels o k body based on the context it is used
func (o *GetAlertLabelsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.CommonResponse
	if err := o.CommonResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *GetAlertLabelsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAlertLabelsOKBody) UnmarshalBinary(b []byte) error {
	var res GetAlertLabelsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
