// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetAlertLabelsParams creates a new GetAlertLabelsParams object
//
// There are no default values defined in the spec.
func NewGetAlertLabelsParams() GetAlertLabelsParams {

	return GetAlertLabelsParams{}
}

// GetAlertLabelsParams contains all the bound params for the get alert labels operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAlertLabels
type GetAlertLabelsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*标签名称
	  Required: true
	  In: path
	*/
	Labelname string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAlertLabelsParams() beforehand.
func (o *GetAlertLabelsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rLabelname, rhkLabelname, _ := route.Params.GetOK("labelname")
	if err := o.bindLabelname(rLabelname, rhkLabelname, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindLabelname binds and validates parameter Labelname from path.
func (o *GetAlertLabelsParams) bindLabelname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Labelname = raw

	return nil
}
