// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"csjk-bk/models"
)

// GetAlertLabelNamesHandlerFunc turns a function with the right signature into a get alert label names handler
type GetAlertLabelNamesHandlerFunc func(GetAlertLabelNamesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAlertLabelNamesHandlerFunc) Handle(params GetAlertLabelNamesParams) middleware.Responder {
	return fn(params)
}

// GetAlertLabelNamesHandler interface for that can handle valid get alert label names params
type GetAlertLabelNamesHandler interface {
	Handle(GetAlertLabelNamesParams) middleware.Responder
}

// NewGetAlertLabelNames creates a new http.Handler for the get alert label names operation
func NewGetAlertLabelNames(ctx *middleware.Context, handler GetAlertLabelNamesHandler) *GetAlertLabelNames {
	return &GetAlertLabelNames{Context: ctx, Handler: handler}
}

/*
	GetAlertLabelNames swagger:route GET /alerts/labels alert getAlertLabelNames

获取所有报警标签的名称.

获取所有报警标签的名称.
*/
type GetAlertLabelNames struct {
	Context *middleware.Context
	Handler GetAlertLabelNamesHandler
}

func (o *GetAlertLabelNames) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAlertLabelNamesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAlertLabelNamesOKBody get alert label names o k body
//
// swagger:model GetAlertLabelNamesOKBody
type GetAlertLabelNamesOKBody struct {
	models.CommonResponse

	// results
	Results []string `json:"results"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *GetAlertLabelNamesOKBody) UnmarshalJSON(raw []byte) error {
	// GetAlertLabelNamesOKBodyAO0
	var getAlertLabelNamesOKBodyAO0 models.CommonResponse
	if err := swag.ReadJSON(raw, &getAlertLabelNamesOKBodyAO0); err != nil {
		return err
	}
	o.CommonResponse = getAlertLabelNamesOKBodyAO0

	// GetAlertLabelNamesOKBodyAO1
	var dataGetAlertLabelNamesOKBodyAO1 struct {
		Results []string `json:"results"`
	}
	if err := swag.ReadJSON(raw, &dataGetAlertLabelNamesOKBodyAO1); err != nil {
		return err
	}

	o.Results = dataGetAlertLabelNamesOKBodyAO1.Results

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o GetAlertLabelNamesOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	getAlertLabelNamesOKBodyAO0, err := swag.WriteJSON(o.CommonResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, getAlertLabelNamesOKBodyAO0)
	var dataGetAlertLabelNamesOKBodyAO1 struct {
		Results []string `json:"results"`
	}

	dataGetAlertLabelNamesOKBodyAO1.Results = o.Results

	jsonDataGetAlertLabelNamesOKBodyAO1, errGetAlertLabelNamesOKBodyAO1 := swag.WriteJSON(dataGetAlertLabelNamesOKBodyAO1)
	if errGetAlertLabelNamesOKBodyAO1 != nil {
		return nil, errGetAlertLabelNamesOKBodyAO1
	}
	_parts = append(_parts, jsonDataGetAlertLabelNamesOKBodyAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this get alert label names o k body
func (o *GetAlertLabelNamesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.CommonResponse
	if err := o.CommonResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this get alert label names o k body based on the context it is used
func (o *GetAlertLabelNamesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.CommonResponse
	if err := o.CommonResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *GetAlertLabelNamesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAlertLabelNamesOKBody) UnmarshalBinary(b []byte) error {
	var res GetAlertLabelNamesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
