// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"csjk-bk/models"
)

// GetAlertLabelsOKCode is the HTTP code returned for type GetAlertLabelsOK
const GetAlertLabelsOKCode int = 200

/*
GetAlertLabelsOK 成功响应

swagger:response getAlertLabelsOK
*/
type GetAlertLabelsOK struct {

	/*
	  In: Body
	*/
	Payload *GetAlertLabelsOKBody `json:"body,omitempty"`
}

// NewGetAlertLabelsOK creates GetAlertLabelsOK with default headers values
func NewGetAlertLabelsOK() *GetAlertLabelsOK {

	return &GetAlertLabelsOK{}
}

// WithPayload adds the payload to the get alert labels o k response
func (o *GetAlertLabelsOK) WithPayload(payload *GetAlertLabelsOKBody) *GetAlertLabelsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get alert labels o k response
func (o *GetAlertLabelsOK) SetPayload(payload *GetAlertLabelsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlertLabelsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAlertLabelsBadRequestCode is the HTTP code returned for type GetAlertLabelsBadRequest
const GetAlertLabelsBadRequestCode int = 400

/*
GetAlertLabelsBadRequest 请求参数错误

swagger:response getAlertLabelsBadRequest
*/
type GetAlertLabelsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.StandardResponse `json:"body,omitempty"`
}

// NewGetAlertLabelsBadRequest creates GetAlertLabelsBadRequest with default headers values
func NewGetAlertLabelsBadRequest() *GetAlertLabelsBadRequest {

	return &GetAlertLabelsBadRequest{}
}

// WithPayload adds the payload to the get alert labels bad request response
func (o *GetAlertLabelsBadRequest) WithPayload(payload *models.StandardResponse) *GetAlertLabelsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get alert labels bad request response
func (o *GetAlertLabelsBadRequest) SetPayload(payload *models.StandardResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlertLabelsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAlertLabelsInternalServerErrorCode is the HTTP code returned for type GetAlertLabelsInternalServerError
const GetAlertLabelsInternalServerErrorCode int = 500

/*
GetAlertLabelsInternalServerError 内部服务错误

swagger:response getAlertLabelsInternalServerError
*/
type GetAlertLabelsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.StandardResponse `json:"body,omitempty"`
}

// NewGetAlertLabelsInternalServerError creates GetAlertLabelsInternalServerError with default headers values
func NewGetAlertLabelsInternalServerError() *GetAlertLabelsInternalServerError {

	return &GetAlertLabelsInternalServerError{}
}

// WithPayload adds the payload to the get alert labels internal server error response
func (o *GetAlertLabelsInternalServerError) WithPayload(payload *models.StandardResponse) *GetAlertLabelsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get alert labels internal server error response
func (o *GetAlertLabelsInternalServerError) SetPayload(payload *models.StandardResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlertLabelsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
