// Code generated by go-swagger; DO NOT EDIT.

// Package restapi CSJK API
//
//	API of the CSJK Project.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/v1
//	Version: 0.0.1
//	Contact: <hecheng@nscc-tj.cn>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
