// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API of the CSJK Project.",
    "title": "CSJK API",
    "contact": {
      "email": "hecheng@nscc-tj.cn"
    },
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/alerts/firing": {
      "get": {
        "description": "前置条件:\n  1) 不同报警/事件汇集点在 Alertmanager. 使用标签 source 字段标识报警来源, 如带内(inband)、带外(outband)、事件(event);\n  2) 报警标签必须包含: source(报警来源), severity(报警级别, 不同来源解释不同级别);\n\n使用方式:\n- 报警管理.活跃事件和报警\n  - 分屏显示(开): 不同类别报警对应的屏与报警数量统计数据通过不同 API 请求. 示例请求带外报警数据: GET \u003cbasePath\u003e/alerts/firing?filter=souorce=outband\u0026page=\u0026page_size=\n  - 分屏显示(关): 无需传递filter参数, 所有数据统一返回.\n",
        "tags": [
          "alert"
        ],
        "summary": "获取活跃报警信息.",
        "operationId": "getFiringAlerts",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi",
            "description": "用于筛选警报的匹配列表.",
            "name": "filter",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "default": 1,
            "description": "页码",
            "name": "page",
            "in": "query",
            "required": true
          },
          {
            "maximum": 1000,
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "default": 10,
            "description": "页数据条目数",
            "name": "page_size",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "获取活跃报警数据",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/CommonResponse"
                },
                {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "object",
                      "properties": {
                        "alerts": {
                          "$ref": "#/definitions/Alerts"
                        },
                        "severity_count": {
                          "type": "object",
                          "properties": {
                            "event": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            },
                            "inband": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            },
                            "outband": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "examples": {
              "application/json": {
                "count": 100,
                "detail": "",
                "next": "/alerts/firing/all?page=2\u0026page_size=10",
                "previous": "",
                "results": {
                  "alerts": [
                    {
                      "annotations": {
                        "description": "happy every day",
                        "summary": "happy every day"
                      },
                      "endsat": null,
                      "fingerprint": "abc123",
                      "generatorurl": "http://example.com/alert1",
                      "id": 1,
                      "labels": {
                        "cluster": "test",
                        "severity": "INFO",
                        "source": "inband"
                      },
                      "operation": "auto",
                      "responder": "alice",
                      "startsat": "2025-08-20T02:50:00Z",
                      "status": "firing"
                    }
                  ],
                  "statistic": {
                    "event": {
                      "DISASTER": 1,
                      "INFO": 10,
                      "SEVERITY": 3,
                      "WARN": 7
                    },
                    "inband": {
                      "DISASTER": 1,
                      "INFO": 10,
                      "SEVERITY": 3,
                      "WARN": 7
                    },
                    "outband": {
                      "lcr": 5,
                      "lnc": 4,
                      "lnr": 6,
                      "ucr": 2,
                      "unc": 3,
                      "unr": 1
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          },
          "500": {
            "description": "内部服务错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          }
        }
      }
    },
    "/alerts/history": {
      "post": {
        "description": "前置条件:\n  1) 数据来源统一, 所有事件与报警汇聚点为 Alertmanager, 均存储在 PG.Alert 相关表中;\n  2) 前端使用的标签名与标签对应值返回应该与报警内容信息保持一致或者能够唯一映射;\n\n使用方式:\n  为保持良好扩展性, 该 API 不会固定具体筛选Labels Key与Annotations Key. 均由前端自己确认 Key 与 Value, 传递给后端进行筛选.\n  - 报警管理.历史事件和报警\n    - 分屏显示(开): 该 API 均可使用, 只需传递对应筛选参数即可.\n    - 分屏显示(关): 不同分屏表示的类别需要传递必须参数, 如带内报警, 则需要在body.labels中传递 source: [\"inband\"].\n",
        "tags": [
          "alert"
        ],
        "summary": "获取历史报警信息.",
        "operationId": "postAlertHistory",
        "parameters": [
          {
            "description": "查询参数",
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "annotations": {
                  "description": "用于筛选警报的注解键值对, 支持多个值",
                  "type": "object",
                  "additionalProperties": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "end": {
                  "description": "查询结束时间",
                  "type": "string",
                  "format": "date-time"
                },
                "labels": {
                  "description": "用于筛选警报的标签键值对, 支持多个值",
                  "type": "object",
                  "additionalProperties": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "page": {
                  "description": "页码",
                  "type": "integer",
                  "format": "int64"
                },
                "page_size": {
                  "description": "页数据条目数",
                  "type": "integer",
                  "format": "int64"
                },
                "start": {
                  "description": "查询开始时间",
                  "type": "string",
                  "format": "date-time"
                },
                "status": {
                  "description": "报警状态, 可选值包括 firing, resolved",
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "获取活跃报警数据",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/CommonResponse"
                },
                {
                  "$ref": "#/definitions/Alerts"
                }
              ]
            },
            "examples": {
              "application/json": {
                "count": 100,
                "detail": "",
                "next": "",
                "previous": "",
                "results": [
                  {
                    "annotations": {
                      "description": "happy every day",
                      "summary": "happy every day"
                    },
                    "endsat": "",
                    "fingerprint": "abc123",
                    "generatorurl": "http://example.com/alert1",
                    "id": 1,
                    "labels": {
                      "cluster": "test",
                      "severity": "INFO",
                      "source": "inband"
                    },
                    "operation": "auto",
                    "responder": "alice",
                    "startsat": "2025-08-20T02:50:00Z",
                    "status": "firing"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          },
          "500": {
            "description": "内部服务错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          }
        }
      }
    },
    "/slurm/users": {
      "get": {
        "description": "获取 slurm 所有用户信息, 以列表形式返回. 该 API 用户\"资源管理-资源监控, 过滤面板中用户控件\". 该 API 由科大提供.",
        "tags": [
          "slurm",
          "kd"
        ],
        "summary": "获取 slurm 所有用户信息, 以列表形式返回.",
        "operationId": "getSlurmUsers",
        "responses": {
          "200": {
            "description": "成功响应",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/CommonResponse"
                },
                {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "description": "用户ID, 对应Linux系统UID.",
                            "type": "integer",
                            "format": "int64"
                          },
                          "name": {
                            "description": "用户名称",
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "examples": {
              "application/json": {
                "count": "100",
                "detail": "",
                "next": "",
                "previous": "",
                "results": [
                  {
                    "id": 10001,
                    "name": "muqali"
                  },
                  {
                    "id": 10002,
                    "name": "hc"
                  },
                  {
                    "id": 10003,
                    "name": "txy"
                  }
                ]
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Alert": {
      "type": "object",
      "properties": {
        "Annotaions": {
          "description": "报警标签",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "Endsat": {
          "description": "报警结束时间",
          "type": "string",
          "format": "date-time"
        },
        "Fingerprint": {
          "description": "报警指纹",
          "type": "string"
        },
        "Generatorurl": {
          "description": "报警生成链接",
          "type": "string"
        },
        "ID": {
          "description": "数据库中报警ID",
          "type": "integer",
          "format": "int64"
        },
        "Labels": {
          "description": "报警标签",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "Operation": {
          "description": "报警处理方式",
          "type": "string"
        },
        "Responder": {
          "description": "报警处理人",
          "type": "string"
        },
        "Startsat": {
          "description": "报警开始时间",
          "type": "string",
          "format": "date-time"
        },
        "Status": {
          "description": "报警状态",
          "type": "string"
        }
      }
    },
    "Alerts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Alert"
      }
    },
    "CommonResponse": {
      "type": "object",
      "required": [
        "count",
        "next",
        "previous",
        "detail"
      ],
      "properties": {
        "count": {
          "description": "若请求为分页模式, 表示数据条目总数量, 否则为 -1",
          "type": "integer",
          "format": "int64",
          "default": -1
        },
        "detail": {
          "description": "若响应码非200, 将原因写到该字段",
          "type": "string"
        },
        "next": {
          "description": "若请求为分页模式, 返回下一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "previous": {
          "description": "若请求为分页模式, 返回上一页请求的URL",
          "type": "string",
          "format": "uri"
        }
      }
    },
    "StandardResponse": {
      "type": "object",
      "required": [
        "count",
        "next",
        "previous",
        "results",
        "detail"
      ],
      "properties": {
        "count": {
          "description": "若请求为分页模式, 表示数据条目总数量, 否则为 -1",
          "type": "integer",
          "format": "int64",
          "default": -1
        },
        "detail": {
          "description": "若响应码非200, 将原因写到该字段",
          "type": "string"
        },
        "next": {
          "description": "若请求为分页模式, 返回下一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "previous": {
          "description": "若请求为分页模式, 返回上一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "results": {
          "description": "实际数据内容 (不同API返回的结构不同)",
          "type": "object"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API of the CSJK Project.",
    "title": "CSJK API",
    "contact": {
      "email": "hecheng@nscc-tj.cn"
    },
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/alerts/firing": {
      "get": {
        "description": "前置条件:\n  1) 不同报警/事件汇集点在 Alertmanager. 使用标签 source 字段标识报警来源, 如带内(inband)、带外(outband)、事件(event);\n  2) 报警标签必须包含: source(报警来源), severity(报警级别, 不同来源解释不同级别);\n\n使用方式:\n- 报警管理.活跃事件和报警\n  - 分屏显示(开): 不同类别报警对应的屏与报警数量统计数据通过不同 API 请求. 示例请求带外报警数据: GET \u003cbasePath\u003e/alerts/firing?filter=souorce=outband\u0026page=\u0026page_size=\n  - 分屏显示(关): 无需传递filter参数, 所有数据统一返回.\n",
        "tags": [
          "alert"
        ],
        "summary": "获取活跃报警信息.",
        "operationId": "getFiringAlerts",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi",
            "description": "用于筛选警报的匹配列表.",
            "name": "filter",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "default": 1,
            "description": "页码",
            "name": "page",
            "in": "query",
            "required": true
          },
          {
            "maximum": 1000,
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "default": 10,
            "description": "页数据条目数",
            "name": "page_size",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "获取活跃报警数据",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/CommonResponse"
                },
                {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "object",
                      "properties": {
                        "alerts": {
                          "$ref": "#/definitions/Alerts"
                        },
                        "severity_count": {
                          "type": "object",
                          "properties": {
                            "event": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            },
                            "inband": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            },
                            "outband": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "examples": {
              "application/json": {
                "count": 100,
                "detail": "",
                "next": "/alerts/firing/all?page=2\u0026page_size=10",
                "previous": "",
                "results": {
                  "alerts": [
                    {
                      "annotations": {
                        "description": "happy every day",
                        "summary": "happy every day"
                      },
                      "endsat": null,
                      "fingerprint": "abc123",
                      "generatorurl": "http://example.com/alert1",
                      "id": 1,
                      "labels": {
                        "cluster": "test",
                        "severity": "INFO",
                        "source": "inband"
                      },
                      "operation": "auto",
                      "responder": "alice",
                      "startsat": "2025-08-20T02:50:00Z",
                      "status": "firing"
                    }
                  ],
                  "statistic": {
                    "event": {
                      "DISASTER": 1,
                      "INFO": 10,
                      "SEVERITY": 3,
                      "WARN": 7
                    },
                    "inband": {
                      "DISASTER": 1,
                      "INFO": 10,
                      "SEVERITY": 3,
                      "WARN": 7
                    },
                    "outband": {
                      "lcr": 5,
                      "lnc": 4,
                      "lnr": 6,
                      "ucr": 2,
                      "unc": 3,
                      "unr": 1
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          },
          "500": {
            "description": "内部服务错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          }
        }
      }
    },
    "/alerts/history": {
      "post": {
        "description": "前置条件:\n  1) 数据来源统一, 所有事件与报警汇聚点为 Alertmanager, 均存储在 PG.Alert 相关表中;\n  2) 前端使用的标签名与标签对应值返回应该与报警内容信息保持一致或者能够唯一映射;\n\n使用方式:\n  为保持良好扩展性, 该 API 不会固定具体筛选Labels Key与Annotations Key. 均由前端自己确认 Key 与 Value, 传递给后端进行筛选.\n  - 报警管理.历史事件和报警\n    - 分屏显示(开): 该 API 均可使用, 只需传递对应筛选参数即可.\n    - 分屏显示(关): 不同分屏表示的类别需要传递必须参数, 如带内报警, 则需要在body.labels中传递 source: [\"inband\"].\n",
        "tags": [
          "alert"
        ],
        "summary": "获取历史报警信息.",
        "operationId": "postAlertHistory",
        "parameters": [
          {
            "description": "查询参数",
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "annotations": {
                  "description": "用于筛选警报的注解键值对, 支持多个值",
                  "type": "object",
                  "additionalProperties": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "end": {
                  "description": "查询结束时间",
                  "type": "string",
                  "format": "date-time"
                },
                "labels": {
                  "description": "用于筛选警报的标签键值对, 支持多个值",
                  "type": "object",
                  "additionalProperties": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "page": {
                  "description": "页码",
                  "type": "integer",
                  "format": "int64"
                },
                "page_size": {
                  "description": "页数据条目数",
                  "type": "integer",
                  "format": "int64"
                },
                "start": {
                  "description": "查询开始时间",
                  "type": "string",
                  "format": "date-time"
                },
                "status": {
                  "description": "报警状态, 可选值包括 firing, resolved",
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "获取活跃报警数据",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/CommonResponse"
                },
                {
                  "$ref": "#/definitions/Alerts"
                }
              ]
            },
            "examples": {
              "application/json": {
                "count": 100,
                "detail": "",
                "next": "",
                "previous": "",
                "results": [
                  {
                    "annotations": {
                      "description": "happy every day",
                      "summary": "happy every day"
                    },
                    "endsat": "",
                    "fingerprint": "abc123",
                    "generatorurl": "http://example.com/alert1",
                    "id": 1,
                    "labels": {
                      "cluster": "test",
                      "severity": "INFO",
                      "source": "inband"
                    },
                    "operation": "auto",
                    "responder": "alice",
                    "startsat": "2025-08-20T02:50:00Z",
                    "status": "firing"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          },
          "500": {
            "description": "内部服务错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          }
        }
      }
    },
    "/slurm/users": {
      "get": {
        "description": "获取 slurm 所有用户信息, 以列表形式返回. 该 API 用户\"资源管理-资源监控, 过滤面板中用户控件\". 该 API 由科大提供.",
        "tags": [
          "slurm",
          "kd"
        ],
        "summary": "获取 slurm 所有用户信息, 以列表形式返回.",
        "operationId": "getSlurmUsers",
        "responses": {
          "200": {
            "description": "成功响应",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/CommonResponse"
                },
                {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/ResultsItems0"
                      }
                    }
                  }
                }
              ]
            },
            "examples": {
              "application/json": {
                "count": "100",
                "detail": "",
                "next": "",
                "previous": "",
                "results": [
                  {
                    "id": 10001,
                    "name": "muqali"
                  },
                  {
                    "id": 10002,
                    "name": "hc"
                  },
                  {
                    "id": 10003,
                    "name": "txy"
                  }
                ]
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Alert": {
      "type": "object",
      "properties": {
        "Annotaions": {
          "description": "报警标签",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "Endsat": {
          "description": "报警结束时间",
          "type": "string",
          "format": "date-time"
        },
        "Fingerprint": {
          "description": "报警指纹",
          "type": "string"
        },
        "Generatorurl": {
          "description": "报警生成链接",
          "type": "string"
        },
        "ID": {
          "description": "数据库中报警ID",
          "type": "integer",
          "format": "int64"
        },
        "Labels": {
          "description": "报警标签",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "Operation": {
          "description": "报警处理方式",
          "type": "string"
        },
        "Responder": {
          "description": "报警处理人",
          "type": "string"
        },
        "Startsat": {
          "description": "报警开始时间",
          "type": "string",
          "format": "date-time"
        },
        "Status": {
          "description": "报警状态",
          "type": "string"
        }
      }
    },
    "Alerts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Alert"
      }
    },
    "CommonResponse": {
      "type": "object",
      "required": [
        "count",
        "next",
        "previous",
        "detail"
      ],
      "properties": {
        "count": {
          "description": "若请求为分页模式, 表示数据条目总数量, 否则为 -1",
          "type": "integer",
          "format": "int64",
          "default": -1
        },
        "detail": {
          "description": "若响应码非200, 将原因写到该字段",
          "type": "string"
        },
        "next": {
          "description": "若请求为分页模式, 返回下一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "previous": {
          "description": "若请求为分页模式, 返回上一页请求的URL",
          "type": "string",
          "format": "uri"
        }
      }
    },
    "GetFiringAlertsOKBodyAO1Results": {
      "type": "object",
      "properties": {
        "alerts": {
          "$ref": "#/definitions/Alerts"
        },
        "severity_count": {
          "type": "object",
          "properties": {
            "event": {
              "type": "object",
              "additionalProperties": {
                "type": "integer",
                "format": "int64"
              }
            },
            "inband": {
              "type": "object",
              "additionalProperties": {
                "type": "integer",
                "format": "int64"
              }
            },
            "outband": {
              "type": "object",
              "additionalProperties": {
                "type": "integer",
                "format": "int64"
              }
            }
          }
        }
      }
    },
    "GetFiringAlertsOKBodyAO1ResultsSeverityCount": {
      "type": "object",
      "properties": {
        "event": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int64"
          }
        },
        "inband": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int64"
          }
        },
        "outband": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int64"
          }
        }
      }
    },
    "ResultsItems0": {
      "type": "object",
      "properties": {
        "id": {
          "description": "用户ID, 对应Linux系统UID.",
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "description": "用户名称",
          "type": "string"
        }
      }
    },
    "StandardResponse": {
      "type": "object",
      "required": [
        "count",
        "next",
        "previous",
        "results",
        "detail"
      ],
      "properties": {
        "count": {
          "description": "若请求为分页模式, 表示数据条目总数量, 否则为 -1",
          "type": "integer",
          "format": "int64",
          "default": -1
        },
        "detail": {
          "description": "若响应码非200, 将原因写到该字段",
          "type": "string"
        },
        "next": {
          "description": "若请求为分页模式, 返回下一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "previous": {
          "description": "若请求为分页模式, 返回上一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "results": {
          "description": "实际数据内容 (不同API返回的结构不同)",
          "type": "object"
        }
      }
    }
  }
}`))
}
