// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API of the CSJK Project.",
    "title": "CSJK API",
    "contact": {
      "email": "hecheng@nscc-tj.cn"
    },
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/alerts/firing/all": {
      "get": {
        "description": "以分页方式返回所有活跃报警信息, 该 API 为报警管理-活跃时间和报警页面中 \"非分屏\" 报警信息请求.",
        "tags": [
          "alerts"
        ],
        "summary": "获取活跃报警",
        "operationId": "getFiringAlertsAll",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "default": 1,
            "description": "页码",
            "name": "page",
            "in": "query",
            "required": true
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "default": 1,
            "description": "页数据条目数",
            "name": "page_size",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "成功响应",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/StandardResponse"
                },
                {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "object",
                      "properties": {
                        "alerts": {
                          "$ref": "#/definitions/Alerts"
                        },
                        "statistic": {
                          "type": "object",
                          "properties": {
                            "event": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            },
                            "inband": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            },
                            "outband": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "examples": {
              "application/json": {
                "count": 100,
                "detail": "",
                "next": "/alerts/firing/all?page=2\u0026page_size=10",
                "previous": "",
                "results": {
                  "alerts": [
                    {
                      "endsat": null,
                      "fingerprint": "abc123",
                      "generatorurl": "http://example.com/alert1",
                      "id": 1,
                      "operation": "auto",
                      "responder": "alice",
                      "startsat": "2025-08-20T02:50:00Z",
                      "status": "firing"
                    }
                  ],
                  "statistic": {
                    "event": {
                      "DISASTER": 1,
                      "INFO": 10,
                      "SEVERITY": 3,
                      "WARN": 7
                    },
                    "inband": {
                      "DISASTER": 1,
                      "INFO": 10,
                      "SEVERITY": 3,
                      "WARN": 7
                    },
                    "outband": {
                      "lcr": 5,
                      "lnc": 4,
                      "lnr": 6,
                      "ucr": 2,
                      "unc": 3,
                      "unr": 1
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          },
          "500": {
            "description": "内部服务错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Alert": {
      "type": "object",
      "properties": {
        "Annotaions": {
          "description": "报警标签",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "Endsat": {
          "description": "报警结束时间",
          "type": "string",
          "format": "date-time"
        },
        "Fingerprint": {
          "description": "报警指纹",
          "type": "string"
        },
        "Generatorurl": {
          "description": "报警生成链接",
          "type": "string"
        },
        "ID": {
          "description": "数据库中报警ID",
          "type": "integer",
          "format": "int64"
        },
        "Labels": {
          "description": "报警标签",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "Operation": {
          "description": "报警处理方式",
          "type": "string"
        },
        "Responder": {
          "description": "报警处理人",
          "type": "string"
        },
        "Startsat": {
          "description": "报警开始时间",
          "type": "string",
          "format": "date-time"
        },
        "Status": {
          "description": "报警状态",
          "type": "string"
        }
      }
    },
    "Alerts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Alert"
      }
    },
    "StandardResponse": {
      "type": "object",
      "properties": {
        "count": {
          "description": "若请求为分页模式, 表示数据条目总数量, 否则为 -1",
          "type": "integer",
          "format": "int64",
          "default": -1
        },
        "detail": {
          "description": "若响应码非200, 将原因写到该字段",
          "type": "string"
        },
        "next": {
          "description": "若请求为分页模式, 返回下一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "previous": {
          "description": "若请求为分页模式, 返回上一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "result": {
          "description": "实际数据内容 (不同API返回的结构不同)",
          "type": "object"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API of the CSJK Project.",
    "title": "CSJK API",
    "contact": {
      "email": "hecheng@nscc-tj.cn"
    },
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/alerts/firing/all": {
      "get": {
        "description": "以分页方式返回所有活跃报警信息, 该 API 为报警管理-活跃时间和报警页面中 \"非分屏\" 报警信息请求.",
        "tags": [
          "alerts"
        ],
        "summary": "获取活跃报警",
        "operationId": "getFiringAlertsAll",
        "parameters": [
          {
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "default": 1,
            "description": "页码",
            "name": "page",
            "in": "query",
            "required": true
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "format": "int64",
            "default": 1,
            "description": "页数据条目数",
            "name": "page_size",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "成功响应",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/definitions/StandardResponse"
                },
                {
                  "type": "object",
                  "properties": {
                    "results": {
                      "type": "object",
                      "properties": {
                        "alerts": {
                          "$ref": "#/definitions/Alerts"
                        },
                        "statistic": {
                          "type": "object",
                          "properties": {
                            "event": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            },
                            "inband": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            },
                            "outband": {
                              "type": "object",
                              "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "examples": {
              "application/json": {
                "count": 100,
                "detail": "",
                "next": "/alerts/firing/all?page=2\u0026page_size=10",
                "previous": "",
                "results": {
                  "alerts": [
                    {
                      "endsat": null,
                      "fingerprint": "abc123",
                      "generatorurl": "http://example.com/alert1",
                      "id": 1,
                      "operation": "auto",
                      "responder": "alice",
                      "startsat": "2025-08-20T02:50:00Z",
                      "status": "firing"
                    }
                  ],
                  "statistic": {
                    "event": {
                      "DISASTER": 1,
                      "INFO": 10,
                      "SEVERITY": 3,
                      "WARN": 7
                    },
                    "inband": {
                      "DISASTER": 1,
                      "INFO": 10,
                      "SEVERITY": 3,
                      "WARN": 7
                    },
                    "outband": {
                      "lcr": 5,
                      "lnc": 4,
                      "lnr": 6,
                      "ucr": 2,
                      "unc": 3,
                      "unr": 1
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          },
          "500": {
            "description": "内部服务错误",
            "schema": {
              "$ref": "#/definitions/StandardResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Alert": {
      "type": "object",
      "properties": {
        "Annotaions": {
          "description": "报警标签",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "Endsat": {
          "description": "报警结束时间",
          "type": "string",
          "format": "date-time"
        },
        "Fingerprint": {
          "description": "报警指纹",
          "type": "string"
        },
        "Generatorurl": {
          "description": "报警生成链接",
          "type": "string"
        },
        "ID": {
          "description": "数据库中报警ID",
          "type": "integer",
          "format": "int64"
        },
        "Labels": {
          "description": "报警标签",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "Operation": {
          "description": "报警处理方式",
          "type": "string"
        },
        "Responder": {
          "description": "报警处理人",
          "type": "string"
        },
        "Startsat": {
          "description": "报警开始时间",
          "type": "string",
          "format": "date-time"
        },
        "Status": {
          "description": "报警状态",
          "type": "string"
        }
      }
    },
    "Alerts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Alert"
      }
    },
    "GetFiringAlertsAllOKBodyAO1Results": {
      "type": "object",
      "properties": {
        "alerts": {
          "$ref": "#/definitions/Alerts"
        },
        "statistic": {
          "type": "object",
          "properties": {
            "event": {
              "type": "object",
              "additionalProperties": {
                "type": "integer",
                "format": "int64"
              }
            },
            "inband": {
              "type": "object",
              "additionalProperties": {
                "type": "integer",
                "format": "int64"
              }
            },
            "outband": {
              "type": "object",
              "additionalProperties": {
                "type": "integer",
                "format": "int64"
              }
            }
          }
        }
      }
    },
    "GetFiringAlertsAllOKBodyAO1ResultsStatistic": {
      "type": "object",
      "properties": {
        "event": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int64"
          }
        },
        "inband": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int64"
          }
        },
        "outband": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int64"
          }
        }
      }
    },
    "StandardResponse": {
      "type": "object",
      "properties": {
        "count": {
          "description": "若请求为分页模式, 表示数据条目总数量, 否则为 -1",
          "type": "integer",
          "format": "int64",
          "default": -1
        },
        "detail": {
          "description": "若响应码非200, 将原因写到该字段",
          "type": "string"
        },
        "next": {
          "description": "若请求为分页模式, 返回下一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "previous": {
          "description": "若请求为分页模式, 返回上一页请求的URL",
          "type": "string",
          "format": "uri"
        },
        "result": {
          "description": "实际数据内容 (不同API返回的结构不同)",
          "type": "object"
        }
      }
    }
  }
}`))
}
