// Code generated by go-swagger; DO NOT EDIT.

package slurm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSlurmUsersOKCode is the HTTP code returned for type GetSlurmUsersOK
const GetSlurmUsersOKCode int = 200

/*
GetSlurmUsersOK 成功响应

swagger:response getSlurmUsersOK
*/
type GetSlurmUsersOK struct {

	/*
	  In: Body
	*/
	Payload *GetSlurmUsersOKBody `json:"body,omitempty"`
}

// NewGetSlurmUsersOK creates GetSlurmUsersOK with default headers values
func NewGetSlurmUsersOK() *GetSlurmUsersOK {

	return &GetSlurmUsersOK{}
}

// WithPayload adds the payload to the get slurm users o k response
func (o *GetSlurmUsersOK) WithPayload(payload *GetSlurmUsersOKBody) *GetSlurmUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get slurm users o k response
func (o *GetSlurmUsersOK) SetPayload(payload *GetSlurmUsersOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSlurmUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
