// Code generated by go-swagger; DO NOT EDIT.

package alerts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetFiringAlertsAllParams creates a new GetFiringAlertsAllParams object
// with the default values initialized.
func NewGetFiringAlertsAllParams() GetFiringAlertsAllParams {

	var (
		// initialize parameters with default values

		pageDefault     = int64(1)
		pageSizeDefault = int64(1)
	)

	return GetFiringAlertsAllParams{
		Page: pageDefault,

		PageSize: pageSizeDefault,
	}
}

// GetFiringAlertsAllParams contains all the bound params for the get firing alerts all operation
// typically these are obtained from a http.Request
//
// swagger:parameters getFiringAlertsAll
type GetFiringAlertsAllParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*页码
	  Required: true
	  Minimum: 1
	  In: query
	  Default: 1
	*/
	Page int64
	/*页数据条目数
	  Required: true
	  Maximum: 100
	  Minimum: 1
	  In: query
	  Default: 1
	*/
	PageSize int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFiringAlertsAllParams() beforehand.
func (o *GetFiringAlertsAllParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qPage, qhkPage, _ := qs.GetOK("page")
	if err := o.bindPage(qPage, qhkPage, route.Formats); err != nil {
		res = append(res, err)
	}

	qPageSize, qhkPageSize, _ := qs.GetOK("page_size")
	if err := o.bindPageSize(qPageSize, qhkPageSize, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPage binds and validates parameter Page from query.
func (o *GetFiringAlertsAllParams) bindPage(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("page", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("page", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("page", "query", "int64", raw)
	}
	o.Page = value

	if err := o.validatePage(formats); err != nil {
		return err
	}

	return nil
}

// validatePage carries on validations for parameter Page
func (o *GetFiringAlertsAllParams) validatePage(formats strfmt.Registry) error {

	if err := validate.MinimumInt("page", "query", o.Page, 1, false); err != nil {
		return err
	}

	return nil
}

// bindPageSize binds and validates parameter PageSize from query.
func (o *GetFiringAlertsAllParams) bindPageSize(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("page_size", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("page_size", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("page_size", "query", "int64", raw)
	}
	o.PageSize = value

	if err := o.validatePageSize(formats); err != nil {
		return err
	}

	return nil
}

// validatePageSize carries on validations for parameter PageSize
func (o *GetFiringAlertsAllParams) validatePageSize(formats strfmt.Registry) error {

	if err := validate.MinimumInt("page_size", "query", o.PageSize, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("page_size", "query", o.PageSize, 100, false); err != nil {
		return err
	}

	return nil
}
